# Нагадування по Markdown

Надаємо невелике нагадування записів в
[Markdown](https://colab.research.google.com/notebooks/markdown_guide.ipynb) (LaTeX):

Markdown | Preview
--- | ---
`**bold text**` | **bold text**
 \\$\frac{x}{y}\\$ | $\frac{x}{y}$
 \\$p^{x}_{y}\\$ | $p^{x}_{y}$
\\$x \cdot y\\$ | $x \cdot y$
\\$\sqrt{x}\\$ | $\sqrt{x}$
\\$\pi\\$ | $\pi$
\\$\approx\\$ | $\approx$

І ще декілька прикладів:

```markdown
$y=x^2$

$e^{i\pi} + 1 = 0$

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

$\frac{n!}{k!(n-k)!} = {n \choose k}$

$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

 $$
 I =
 \left (\begin{array}{cc}
 1 & 0\\
 0 & 1
 \end{array}\right)
 $$
```

$y=x^2$

$e^{i\pi} + 1 = 0$

$e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i$

$\frac{n!}{k!(n-k)!} = {n \choose k}$

$A_{m,n} =
 \begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n}
 \end{pmatrix}$

$I =
\left (\begin{array}{cc}
1 & 0\\
0 & 1
\end{array}\right)$
 ---

# Завдання 1.
В шаблоні наведені числові вектори $\overline{a}$ та $\overline{b}$. Порахуй наступне:
- сума $\overline{a}$ та $\overline{b}$
- різниця $\overline{a}$ та $\overline{b}$
- сума $\overline{a}$ та $\overline{b}^T$. Поясни отриманий результат.
- матричний добуток (dot product) $\overline{a}$ та $\overline{b}^T$.
- матричний добуток (dot product) $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- добуток Адамара (Hadamard product) $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- ділення $\overline{a}$ та $\overline{b}$. Поясни отриманий результат.
- ділення $\overline{a}$ та $\overline{b}^T$. Поясни отриманий результат.

In [17]:
import numpy as np
# Код оголошення векторів не можна змінювати
a = np.array([[1, 2, 3, 4, 5]])
b = np.array([[1/2, 1, 2, 3, 4]])

In [12]:
res = a + b
res

array([[1.5, 3. , 5. , 7. , 9. ]])

In [13]:
res = a - b
res

array([[0.5, 1. , 1. , 1. , 1. ]])

In [14]:
# Пояснення: Після транспонування вектора b ми додаємо його до вектора a. Оскільки a - це рядковий вектор, а b.T - стовпчиковий вектор, відбувається додавання кожного елемента рядка a до кожного елемента стовпця b.T. В результаті ми отримуємо 5x5 матрицю.
res = a + b.T
res

array([[1.5, 2.5, 3.5, 4.5, 5.5],
       [2. , 3. , 4. , 5. , 6. ],
       [3. , 4. , 5. , 6. , 7. ],
       [4. , 5. , 6. , 7. , 8. ],
       [5. , 6. , 7. , 8. , 9. ]])

In [15]:
res = np.dot(a, b.T)
res

array([[40.5]])

In [22]:
# Пояснення: Ця операція неможлива тому що кількість стовпців вектора а відповідала кількості рядків вектора b, а це можливо тільки після його транспонування як у попередньому випадку 
res = np.dot(a, b.T) 
res

array([[40.5]])

In [23]:
# Пояснення: Добуток Адамара (Hadamard product, elementwise multiplication) - це операція, де кожен елемент однієї матриці множиться на відповідний елемент іншої матриці. Основною вимогою для добутку Адамара є то, що обидві матриці повинні мати однаковий розмір. Результатом є нова матриця, де кожний елемент є добутком відповідних елементів вихідних матриць.
res = np.multiply(a, b)
res

array([[ 0.5,  2. ,  6. , 12. , 20. ]])

In [20]:
# Пояснення: це поелементне ділення, тобто кожний елемент вектора a буде поділено на відповідний елемент вектора b.
res = np.divide(a, b)
res

array([[2.        , 2.        , 1.5       , 1.33333333, 1.25      ]])

In [25]:
# Пояснення: Поелементне ділення неможливе тому np автоматично розширює менший масив, так, щоб операція могла виконуватись поелементно.  
res = np.divide(a, b.T)
res

array([[ 2.        ,  4.        ,  6.        ,  8.        , 10.        ],
       [ 1.        ,  2.        ,  3.        ,  4.        ,  5.        ],
       [ 0.5       ,  1.        ,  1.5       ,  2.        ,  2.5       ],
       [ 0.33333333,  0.66666667,  1.        ,  1.33333333,  1.66666667],
       [ 0.25      ,  0.5       ,  0.75      ,  1.        ,  1.25      ]])

# Завдання 2
В цьому завданні ти навчишся перетворювати вектори за допомогою афінних перетворень.  
Дано вектор:
$$
x =
\left(\begin{array}{cc}
2\\
1
\end{array}\right)
$$


Виконай аналітично наступні завдання задавши матрицю перетворення та застосуй її до вектора $x$:

1. Зменши вектор $x$ в 2 рази по вісі $OX$ та збільш в 3 рази по вісі $OY$.
2. Відобрази вектор $x$ відносно початку координат.
3. Перенеси вектор $x$ на -3 по вісі $OX$ та на 1 по вісі $OY$.
4. Змісти вектор $x$ на 60° по вісі $OY$.
5. Поверни вектор $x$ на 30°.
6. Об'єднай перетворення з кроків 1, 2, 4, 5 в одну матрицю та застосуй її до вектору $x$.

#### 2.1 Зменши вектор  $x$  в 2 рази по вісі  OX  та збільш в 3 рази по вісі  OY .

$$
M_1 =
\left (\begin{array}{cc}
1/2 & 0\\
0 & 3
\end{array}\right)
$$

$$
M_1x =
\left(\begin{array}{cc}
1/2& 0\\
0 & 3
\end{array}\right)
\left (\begin{array}{cc}
2\\
1
\end{array}\right)=
\left(\begin{array}{cc}
1/2 \cdot 2 + 0 \cdot 1\\
0 \cdot 2 + 3 \cdot 1
\end{array}\right)=
\left(\begin{array}{cc}
1\\
3
\end{array}\right)
$$

#### 2.2 Відобрази вектор $x$ відносно початку координат.

$$
M_2 = \left(\begin{array}{cc}
-1 & 0\\
0 & -1
\end{array}\right)
\\
M_2 x = \left(\begin{array}{cc}
-1 & 0 \\
0 & -1
\end{array}\right)
\left(\begin{array}{c}
2 \\
1
\end{array}\right)
\\
M_2 x = \left(\begin{array}{c}
-2 \\
-1
\end{array}\right)
$$

#### 2.3 Перенеси вектор $x$, задавши відповідну матрицю і помноживши на неї,  на -3 по вісі $OX$ та на 1 по вісі $OY$.

$$
M_3 = \left(\begin{array}{ccc}
1 & 0 & -3 \\
0 & 1 & 1 \\
0 & 0 & 1
\end{array}\right)
\\
x = \left(\begin{array}{c} 2 \\ 1 \\ 1 \end{array}\right)
\\
M_3 x = \left(\begin{array}{ccc}
1 & 0 & -3 \\
0 & 1 & 1 \\
0 & 0 & 1
\end{array}\right)
\left(\begin{array}{c}
2 \\
1 \\
1
\end{array}\right)
\\
M_3 x = \left(\begin{array}{c}
-1 \\
2 \\
1
\end{array}\right)
$$

#### 2.4 Змісти вектор $x$ на 60° по вісі $OY$.


$$
M_4 = \begin{pmatrix}
1 & \tan(\theta) \\
0 & 1
\end{pmatrix}
\\
M_4 = \left(\begin{array}{cc}
\frac{1}{2} & -\frac{\sqrt{3}}{2} \\
\frac{\sqrt{3}}{2} & \frac{1}{2}
\end{array}\right)
\\
M_4x = \begin{pmatrix}
1 & \sqrt{3} \\
0 & 1
\end{pmatrix}
\begin{pmatrix}
2 \\
1
\end{pmatrix}
\\
M_4 x = \begin{pmatrix}
3.732 \\
1
\end{pmatrix}
$$

#### 2.5 Поверни вектор $x$ на 30°.

$$
M_5 = \left(\begin{array}{cc}
\cos(30^\circ) & -\sin(30^\circ) \\
\sin(30^\circ) & \cos(30^\circ)
\end{array}\right)
\\
M_5 = \left(\begin{array}{cc}
\frac{\sqrt{3}}{2} & -\frac{1}{2} \\
\frac{1}{2} & \frac{\sqrt{3}}{2}
\end{array}\right)
\\
M_5 x = \left(\begin{array}{cc}
\frac{\sqrt{3}}{2} & -\frac{1}{2} \\
\frac{1}{2} & \frac{\sqrt{3}}{2}
\end{array}\right)
\left(\begin{array}{c}
2 \\
1
\end{array}\right)
\\
M_5 x = \left(\begin{array}{c}
\sqrt{3} - \frac{1}{2} \\
1 + \frac{\sqrt{3}}{2}
\end{array}\right)
$$

#### 2.6 Об'єднай перетворення з кроків 1, 2, 4, 5 в одну матрицю та застосуй її до вектору $x$.

$$
M_6 = M_5 \cdot M_4 \cdot M_2 \cdot M_1 = 
\\
M_2 \cdot M_1 = \left(\begin{array}{cc}
-1 & 0 \\
0 & -1
\end{array}\right)
\left(\begin{array}{cc}
\frac{1}{2} & 0 \\
0 & 3
\end{array}\right) =
\left(\begin{array}{cc}
-\frac{1}{2} & 0 \\
0 & -3
\end{array}\right)
\\
M_4 \cdot M_2M_1 = \left(\begin{array}{cc}
\frac{1}{2} & -\frac{\sqrt{3}}{2} \\
\frac{\sqrt{3}}{2} & \frac{1}{2}
\end{array}\right)
\left(\begin{array}{cc}
-\frac{1}{2} & 0 \\
0 & -3
\end{array}\right) =
\left(\begin{array}{cc}
-\frac{1}{4} & \frac{3\sqrt{3}}{2} \\
-\frac{\sqrt{3}}{4} & -\frac{3}{2}
\end{array}\right)
\\
M_5 \cdot (M_4 \cdot M_2 \cdot M_1) = \left(\begin{array}{cc}
\frac{\sqrt{3}}{2} & -\frac{1}{2} \\
\frac{1}{2} & \frac{\sqrt{3}}{2}
\end{array}\right)
\left(\begin{array}{cc}
-\frac{1}{4} & \frac{3\sqrt{3}}{2} \\
-\frac{\sqrt{3}}{4} & -\frac{3}{2}
\end{array}\right)
\\
M_6 = \left(\begin{array}{cc}
0 & 3 \\
-1/2 & 0
\end{array}\right)
$$

$$
M_6 x = \left(\begin{array}{cc}
0 & 3 \\
-\frac{1}{2} & 0
\end{array}\right)
\left(\begin{array}{c}
2 \\
1
\end{array}\right) =
\left(\begin{array}{c}
0 \cdot 2 + 3 \cdot 1 \\
-\frac{1}{2} \cdot 2 + 0 \cdot 1
\end{array}\right) =
\left(\begin{array}{c}
3 \\
-1
\end{array}\right)
$$

# Завдання 2 (Альтернативне)

In [ ]:
import cv2 as cv
import urllib
import numpy as np
from google.colab.patches import cv2_imshow as cv_imshow

# Read an image
def read_image_by_url(url):
    req = urllib.request.urlopen(url)
    arr = np.asarray(bytearray(req.read()), dtype=np.uint8)
    img = cv.imdecode(arr, -1)
    return img

url = ''

img = read_image_by_url(url)

In [ ]:
cv_imshow(img)